version: '3' 

services:
  bysykkel-client: 
    build: ./src/client/ 
    ports:
      - "3000:3000"
    links:
      - "bysykkel-api"
    depends_on:
      - "bysykkel-api"

  bysykkel-api:
    build:  
      context: ./src/api/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
